--------------------------------------------------------
--  File created - Tuesday-April-16-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESSES
--------------------------------------------------------

  CREATE TABLE "CITIZEN_REGISTRATIONS"."ADDRESSES" 
   (	"ID" NUMBER, 
	"COUNTRY" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"MUNICIPALITY" VARCHAR2(50 BYTE), 
	"POSTAL_CODE" VARCHAR2(10 BYTE), 
	"STREET" VARCHAR2(50 BYTE), 
	"NMBR" VARCHAR2(10 BYTE), 
	"FLOOR" NUMBER, 
	"APARTMENTNO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EDUCATIONS
--------------------------------------------------------

  CREATE TABLE "CITIZEN_REGISTRATIONS"."EDUCATIONS" 
   (	"ID" NUMBER, 
	"TYPE_ID" NUMBER, 
	"INSTITUTION_NAME" VARCHAR2(50 BYTE), 
	"ENROLLMENT_DATE" DATE, 
	"GRADUATION_DATE" DATE, 
	"GRADUATED" NUMBER(1,0), 
	"FINAL_GRADE" NUMBER(3,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EDUCATION_TYPE
--------------------------------------------------------

  CREATE TABLE "CITIZEN_REGISTRATIONS"."EDUCATION_TYPE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GENDER
--------------------------------------------------------

  CREATE TABLE "CITIZEN_REGISTRATIONS"."GENDER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PEOPLE
--------------------------------------------------------

  CREATE TABLE "CITIZEN_REGISTRATIONS"."PEOPLE" 
   (	"ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"MIDDLE_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"GENDER_ID" NUMBER, 
	"HEIGHT" NUMBER, 
	"BIRTH_DATE" DATE, 
	"CURRENT_ADDRESS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PEOPLE_ADDRESSES
--------------------------------------------------------

  CREATE TABLE "CITIZEN_REGISTRATIONS"."PEOPLE_ADDRESSES" 
   (	"PERSON_ID" NUMBER, 
	"ADDRESS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PEOPLE_EDUCATIONS
--------------------------------------------------------

  CREATE TABLE "CITIZEN_REGISTRATIONS"."PEOPLE_EDUCATIONS" 
   (	"PEOPLE_ID" NUMBER, 
	"EDUCAION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CITIZEN_REGISTRATIONS.ADDRESSES
SET DEFINE OFF;
REM INSERTING into CITIZEN_REGISTRATIONS.EDUCATIONS
SET DEFINE OFF;
REM INSERTING into CITIZEN_REGISTRATIONS.EDUCATION_TYPE
SET DEFINE OFF;
Insert into CITIZEN_REGISTRATIONS.EDUCATION_TYPE (ID,NAME) values (1,'None');
Insert into CITIZEN_REGISTRATIONS.EDUCATION_TYPE (ID,NAME) values (2,'Primary');
Insert into CITIZEN_REGISTRATIONS.EDUCATION_TYPE (ID,NAME) values (3,'Secondary');
Insert into CITIZEN_REGISTRATIONS.EDUCATION_TYPE (ID,NAME) values (4,'Bachelor');
Insert into CITIZEN_REGISTRATIONS.EDUCATION_TYPE (ID,NAME) values (5,'Master');
Insert into CITIZEN_REGISTRATIONS.EDUCATION_TYPE (ID,NAME) values (6,'Doctorate');
REM INSERTING into CITIZEN_REGISTRATIONS.GENDER
SET DEFINE OFF;
Insert into CITIZEN_REGISTRATIONS.GENDER (ID,NAME) values (1,'Male');
Insert into CITIZEN_REGISTRATIONS.GENDER (ID,NAME) values (2,'Female');
REM INSERTING into CITIZEN_REGISTRATIONS.PEOPLE
SET DEFINE OFF;
REM INSERTING into CITIZEN_REGISTRATIONS.PEOPLE_ADDRESSES
SET DEFINE OFF;
REM INSERTING into CITIZEN_REGISTRATIONS.PEOPLE_EDUCATIONS
SET DEFINE OFF;
