--------------------------------------------------------
--  File created - Friday-April-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BATTLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TROLL_GAME"."BATTLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BATTLE
--------------------------------------------------------

  CREATE TABLE "TROLL_GAME"."BATTLE" 
   (	"ID" NUMBER, 
	"HUMAN_COUNT" NUMBER, 
	"TROLL_COUNT" NUMBER, 
	"WINNER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BATTLE_LOG
--------------------------------------------------------

  CREATE TABLE "TROLL_GAME"."BATTLE_LOG" 
   (	"ROUND" NUMBER(20,0), 
	"HUMANHP" NUMBER(20,0), 
	"TROLLHP" NUMBER(20,0), 
	"AGGRESSOR" VARCHAR2(20 BYTE), 
	"BATTLE_ID" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TROLL_GAME.BATTLE
SET DEFINE OFF;
Insert into TROLL_GAME.BATTLE (ID,HUMAN_COUNT,TROLL_COUNT,WINNER) values (9,3,3,'Human');
Insert into TROLL_GAME.BATTLE (ID,HUMAN_COUNT,TROLL_COUNT,WINNER) values (10,3,3,'Human');
REM INSERTING into TROLL_GAME.BATTLE_LOG
SET DEFINE OFF;
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (3,8,20,'Troll',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (4,8,10,'Human',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (5,2,10,'Troll',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (6,2,0,'Human',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (7,0,30,'Troll',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (8,20,20,'Human',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (9,14,20,'Troll',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (10,14,10,'Human',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (11,8,10,'Troll',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (12,8,0,'Human',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (13,2,30,'Troll',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (14,2,20,'Human',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (15,0,20,'Troll',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (16,20,10,'Human',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (17,14,10,'Troll',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (18,14,0,'Human',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (1,14,30,'Troll',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (2,14,20,'Human',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (1,14,30,'Troll',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (2,14,20,'Human',9);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (3,8,20,'Troll',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (4,8,10,'Human',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (5,2,10,'Troll',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (6,2,0,'Human',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (7,0,30,'Troll',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (8,20,20,'Human',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (9,14,20,'Troll',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (10,14,10,'Human',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (11,8,10,'Troll',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (12,8,0,'Human',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (13,2,30,'Troll',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (14,2,20,'Human',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (15,0,20,'Troll',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (16,20,10,'Human',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (17,14,10,'Troll',10);
Insert into TROLL_GAME.BATTLE_LOG (ROUND,HUMANHP,TROLLHP,AGGRESSOR,BATTLE_ID) values (18,14,0,'Human',10);
--------------------------------------------------------
--  DDL for Index BATTLE_LOG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TROLL_GAME"."BATTLE_LOG_UK1" ON "TROLL_GAME"."BATTLE_LOG" ("BATTLE_ID", "ROUND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BATTLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TROLL_GAME"."BATTLE_PK" ON "TROLL_GAME"."BATTLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger BATTLE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TROLL_GAME"."BATTLE_TRG" 
BEFORE INSERT ON BATTLE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT BATTLE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TROLL_GAME"."BATTLE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table BATTLE_LOG
--------------------------------------------------------

  ALTER TABLE "TROLL_GAME"."BATTLE_LOG" ADD CONSTRAINT "BATTLE_LOG_UK1" UNIQUE ("BATTLE_ID", "ROUND")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BATTLE
--------------------------------------------------------

  ALTER TABLE "TROLL_GAME"."BATTLE" ADD CONSTRAINT "BATTLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TROLL_GAME"."BATTLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BATTLE_LOG
--------------------------------------------------------

  ALTER TABLE "TROLL_GAME"."BATTLE_LOG" ADD CONSTRAINT "BATTLE_LOG_FK1" FOREIGN KEY ("BATTLE_ID")
	  REFERENCES "TROLL_GAME"."BATTLE" ("ID") ENABLE;
